name: iOS CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-${{ hashFiles('**/*.xcodeproj') }}

      - name: Install dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project GutCheck/GutCheck.xcodeproj

      - name: Build
        run: |
          xcodebuild -project GutCheck/GutCheck.xcodeproj -scheme GutCheck -destination 'platform=iOS Simulator,name=iPhone 16' build

      - name: Run Unit Tests
        run: |
          xcodebuild test -project GutCheck/GutCheck.xcodeproj -scheme GutCheck -destination 'platform=iOS Simulator,name=iPhone 16' -enableCodeCoverage YES

      - name: Upload code coverage (optional)
        if: always()
        run: |
          echo "You can integrate Codecov or Sonar here"
